---
kind: golang.Generate
spec:
  vtProtobufEnabled: false
  baseSpecPath: /messages/
  specs:
    - source: /messages/messages.proto
      genGateway: false
      external: false
---
kind: auto.CI
spec:
  provider: drone
